sudo: false
os:
- linux
language: python
python:
- '2.7'
- '3.5'
env:
  global:
  - CONDA_PREFIX=~/conda
  - CONDA_BIN=~/conda/bin/conda
  - secure: jGS1d4c09NgJMsg5BjE+XcmhIGkKlfdtZq/0ugD0xveuUv8xVRKT7v7K2T3fAoxp0izMsbvlsxO9ZxQEUQKz3liOcUmpqitNSr9h+MgK17lzEeAkuk5baIuHpDLYTEF4Gk5t6H47Dd1MYgV5unhnknTiIUOX1qbJKxUAhr6t1cSmsgVrODDKt0orjgm8XIWYZVjip4WVfxbQCJXqOXYguWfZ0xcq83YXu0I32Uh2YaR02mQDE3C6WdNPXkv0t6wDnYDFrJe//+SnbLwBbl5ElqJljSaoJ9FG+j2W77rvBsF+CQVQ3uA5ViWl3sfRmdw4WrIYSAtxX6D5NrOY3bW41n7fM3wUG+JYFtdGBWRMsNasakO4+vJOom2vfj3OSNB2CQUwSOJFvV0Wn8sQWSGl+2obaTJ59SEAfcXtd3hUS6cxgLeSuxg+5oaLjnvPjQgC7USuzP6e0eA0Q88SzewuduqEIVgASn6uhRksSEqpcT5nJ70wp/+RPA9gSHE8UaziFlCneHrUUMTASmOLRdPflqjp6PWRw/2ZgHjVD1ZaCLrdwTIilpl2q/+uEjQAXogY9+wU2pEKCCIlg0FE2zO4Sz5IKmOOB1UAeFld/6gyK8QFlv3O1cgxtKCoo95Qhumx5hBlq+4X3ZWft/cgzGUgYwe/x9zKn6plWZEbHCBDi0M=
  - secure: F9xTlWEaXeJDPGDJubheS8XVAQB3iVDEvsF96pm1NXbehDswVwdXoL/ngVocgyvzEmNW4CGQALqCH0eBX80JHwN3ScX2l2IKR/PSGm3s3vKAubipfi3BLqpk/YSyrH4JQrsZk+tAGV9ONtnMQDyckbl4AuggnaC8UX/++7ONFKgWVBwkgLGdXgibuSgfGVGtc2vlVjMrpK/w0OEOr09bJUzTPitG/cdqjWikIcTlPZrsjYSkg9PLY7NPDd207iO27+Onlw/dCXeb4OjIzfFgSIG59pdx9NvEU6qoSusit6lyqLwpBr/zyX00Wj6NCrU/T6a+XOhHTn2tuclw7bkEu6vTM2II/+LQrBnhSl6k3CPP3V/bmk6h5cyaQnXcb5Xkh1cqHslmBqnFV7E5GEDrVR0l8wBQBlguykc1+AarAbSp3m/Hj+DC1dDqjR9ToKV+XswdJDy/xeo6RX2lT7gJmfEGdMVJSXHCBaNxl2PgsHHnpW2lKavY5Y3bFCp7ZDtyW6CSEwxy4ffyv88w7pRqQkiQ7MP9QyvkSlWSbI0AGFXqhyCxy6p5k2dLrIHs8bMbnWWiadls1Bk7+HxHKoBCcdpa5roHZ695PhMKRF5VZxOnxYvUwZqQnXChXoYH1083kYUK6n8TUlSo+RsbnOMvVdH++rGq6im6ALYzLtggAeg=
  - secure: mThvfIhPXxq/nD0EeUe2v3JIEnFNzRP7ZIFUXAjJMhc8SITyDBHvuTgHuNmvx3G33bIIqkNMwyt535kuR4+tBVHMi7GuWuDslHiW8Dro1pTx53A9hmdsXEz/aoJaKtW4rsHJLv3TOXjLeUybsVXFzGeZJkUb799//pXE2IRPu6fLaH9Ncu/o59N2MwmNYIRs8RyYEzqfSJ0+Yv1B6/6nmqmhvD2zWRdbmjDeCo4F5liYDziBx7+heJaDlDPPh3EqvrQAOTiFPGm9dB7W6Uc2DBBRIgdk0+rXNc2POtZnUhF+H+KtW0cktvk6PzLQGi1XKbsQ9QkXxGV/6nSDiEfTq5B9xK7uFil/N5J5+dx4decHryN0Qyly733eTlr4FcK30+OtOOz9lRRm2C6L+lc3zTJGl6iAd1GMrFVwFpX+dFG6hb5FdfD+MFy5OaN1dBPfEK2H8dWX4eebMwtXhQ/prLvNncvxJi0Ze7flb6v7t4pB2JVcuxbOfosPPOIsPOIp9OXa6bcjjLZvBbuwdqTYLpfLeNEwsfVJW84XBXvNq50nf79D9ZWgpMOA2yuzJrLjlRWiJwi5MZe0MhpCYM43gynPrE9IHtK3r2go6dyRJIW0Q8V0EL3tx2J41Ll0Ufroelp97OE4npqgCbz/BEaPxJS3crdZa8+d5TJKXM3MDCQ=
install:
- if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh
  -O miniconda.sh; else wget http://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh
  -O miniconda.sh; fi
- bash miniconda.sh -bp $CONDA_PREFIX
- export PATH="$CONDA_PREFIX/bin:$PATH"
- "$CONDA_BIN config --set always_yes yes --set changeps1 no"
- "$CONDA_BIN --version"
- "$CONDA_BIN config --add channels mvdbeek"
- "$CONDA_BIN config --add channels bioconda"
- "$CONDA_BIN config --add channels conda-forge"
- "$CONDA_BIN install bwa cap3 samtools virtualenv conda-build -c bioconda"
- samtools --version
- pip install tox-travis coveralls anaconda-client
- mkdir -p ~/.planemo/ && virtualenv ~/.planemo/gx_venv
- $CONDA_BIN build --python "$TRAVIS_PYTHON_VERSION" conda/multiprocessing-logging
- $CONDA_BIN build --python "$TRAVIS_PYTHON_VERSION" conda/readtagger
script: tox
after_success:
- chmod +x conda/deploy.sh galaxy/deploy.sh
- coveralls
deploy:
- provider: pypi
  skip_cleanup: true
  user: mvdbeek
  password:
    secure: t3Icum4IahHP8eF+e8OEy2d0/Vb+AUd8GWuYM/SoG/Fqf2OBKiyS2fJGfL5N96k4JGzxfIMoV5vNJ/WPiNA3wPluYb8KW6ork2Mp/0UuxHTCkkdmjeGE528qWkprS8F+0N4qDDdK+6k+hOmGdSiiRryCzIz2deAb07npNytnlqbe70CGskTwrBAdxjFmkvjxMje0QSxdFIBNksBt4qd3x1UjMJ14BtYFPSgAXE0HYwEzrFyMLIXoA3kevCKpXYsX8bT7uPpNNKDvyG6hTyKraUPAXv/eX3JfFFu9vURzJQik5UQ+0S1Wc1hyevc9nZkTyIEpPOqmoZvBU0lI/wNGlw0c72VDwLxvJyspq/5HTsQaHih4KJX7jFHjVRbIT/Fu8KKp7gQyAAtEwgj+6SeE++EFDGSlrjqST3lHWjAZE07ODuCH/DS4oSFajrnqu7a481D03cm14FFGr6M6joxbPpylOPSqjJkVvndt06+68zdXtKg8UOHLNmUyLudZez5oEr277MQYtAZkDEVXn8mpysxeh7DdlenLQdQaW3rA65GuIe5F4nGRYX5xYwedXCQEZNWv1LqjMb1zDvlkRQ3l8e1fn8Swrdj+/Z2mZB4kq3tSS3mHL3H9euFHRbzRuE/fRLu1rkyTJH5K99Y5HrjT8C1n75md/BS3lSVggB7zcyc=
  on:
    tags: true
    python: 2.7
- provider: script
  skip_cleanup: true
  script: conda/deploy.sh
  on:
    tags: true
    python: 2.7
- provider: script
  skip_cleanup: true
  script: galaxy/deploy.sh
  on:
    tags: true
    python: 2.7
