package:
  name: tag_reads
  version: "0.1.3"

source:
  fn: tag_reads-0.1.3.tar.gz
  url: https://pypi.python.org/packages/07/9f/712fc901afc4237a18e9721ae278ffb43d0439087ed263415275e0bc091f/tag_reads-0.1.3.tar.gz
  md5: 5df0a8d7d1f4716ac30315dfa84f5ba0

build:
  conda_preserve_egg_dir: False
  entry_points:
    - tag_reads=tag_reads.tag_reads:main
  number: 0

requirements:
  build:
    - python
    - setuptools
    - pysam
    - six

  run:
    - python
    - setuptools
    - pysam
    - six

test:
  # Python imports
  imports:
    - tag_reads

  commands:
    - tag_reads --help

about:
  home: https://github.com/bardin-lab/tag_reads
  license: MIT
  summary: 'Tags reads in BAM files based on alignments in additional BAM files.'
  license_family: MIT
