package:
  name: tag_reads
  version: "0.1.2"

source:
  fn: tag_reads-0.1.2.tar.gz
  url: https://pypi.python.org/packages/43/f6/6e0d0e006f8d71d7e5ec1c12fcad6b8e22343f0c835889270ce522b71f98/tag_reads-0.1.2.tar.gz
  md5: cc5d8370cab883b232d5bd7b77601832

build:
  conda_preserve_egg_dir: False
  entry_points:
    - tag_reads=tag_reads.tag_reads:main
  number: 1

requirements:
  build:
    - python
    - setuptools
    - pysam
    - six

  run:
    - python
    - setuptools
    - pysam
    - six

test:
  # Python imports
  imports:
    - tag_reads

  commands:
    - tag_reads --help

about:
  home: https://github.com/bardin-lab/tag_reads
  license: MIT
  summary: 'Tags reads in BAM files based on alignments in additional BAM files.'
  license_family: MIT
