package:
  name: tag_reads
  version: "0.1.3.1"

source:
  fn: tag_reads-0.1.3.1.tar.gz
  url: https://pypi.python.org/packages/00/c5/fe9cb106ba840bfde601af6472d9c85dd7fb261c2653882b750535c940a9/tag_reads-0.1.3.1.tar.gz
  md5: 2984186052d6dceb0583bb6be506016f

build:
  conda_preserve_egg_dir: False
  entry_points:
    - tag_reads=tag_reads.tag_reads:main
  number: 0

requirements:
  build:
    - python
    - setuptools
    - pysam
    - six

  run:
    - python
    - setuptools
    - pysam
    - six

test:
  # Python imports
  imports:
    - tag_reads

  commands:
    - tag_reads --help

about:
  home: https://github.com/bardin-lab/tag_reads
  license: MIT
  summary: 'Tags reads in BAM files based on alignments in additional BAM files.'
  license_family: MIT
