package:
  name: readtagger
  version: {{ GIT_DESCRIBE_TAG| replace('v', '', 1) }}

source:
  path: ../../

build:
  number: {{ environ.get('GIT_DESCRIBE_NUMBER', 0)}}
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - cached-property
    - biopython
    - bcbiogff
    - click
    - futures
    - setuptools
    - contextlib2
    - shutilwhich  # [not py3k]
    - pysam >=0.9.4
    - six

  run:
    - biopython
    - bcbiogff
    - click
    - futures
    - cached-property
    - cap3
    - sambamba
    - python
    - contextlib2
    - pysam >=0.9.4
    - six
    - shutilwhich  # [not py3k]

test:
  # Python imports
  imports:
    - readtagger

  commands:
    - readtagger --help
    - allow_dovetailing --help
    - add_matesequence --help
    - findcluster --help

about:
  home: https://github.com/bardin-lab/readtagger
  license: MIT
  summary: 'Tags reads in BAM files based on alignments in additional BAM files.'
  license_family: MIT
