{% set name = "multiprocessing-logging" %}
{% set version = "0.2.4" %}
{% set sha256 = "414aad0ce739a3a1d1d026709233bc96846c0f1a9c3994a69c7751b93f6fde43" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/mvdbeek/multiprocessing-logging/archive/v0.2.4.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools
  run:
    - python

test:
  imports:
    - multiprocessing_logging

about:
  home: https://github.com/jruere/multiprocessing-logging
  license: LGPL-3.0
  license_file: LICENSE
  summary: 'Logger for multiprocessing applications'

  description: |
    Logger for multiprocessing applications.

extra:
  recipe-maintainers:
    - mvdbeek
