{% set name = "multiprocessing-logging" %}
{% set version = "0.2.6" %}
{% set sha256 = "695aa489a1f3914e78a54488444ba9567118b35ba25c1af478b768f9b5ad833f" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/mvdbeek/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - python
    - setuptools
  run:
    - python

test:
  imports:
    - multiprocessing_logging

about:
  home: https://github.com/jruere/multiprocessing-logging
  license: LGPL-3.0
  license_file: LICENSE
  summary: 'Logger for multiprocessing applications'

  description: |
    Logger for multiprocessing applications.

extra:
  recipe-maintainers:
    - mvdbeek
